version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: base
    volumes:
      - ./frontend:/home/node/app/src
    container_name: frontend
    expose:
      - '8181'
    ports:
      - '8181:8181'
    networks:
      - app-network
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: base
    volumes:
      - ./backend:/home/node/app/src
    container_name: backend
    expose:
      - '8000'
    ports:
      - '8000:8000'
    networks:
      - app-network
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    env_file:
      - ./backend/.env
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "$${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "$${DB_PASSWORD}"
      MYSQL_PASSWORD: "$${DB_PASSWORD}"
      MYSQL_USER: "$${DB_USERNAME}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
