version: "3"

silent: true

dotenv: ['./backend/.env']

tasks:
  d:up:
    desc: Startup docker containers
    cmds:
      - docker-compose up
  d:up:s:
    desc: Startup docker containers
    cmds:
      - docker-compose -d
  d:down:
    desc: Shutdown docker containers
    cmds:
      - docker-compose down
  d:build:
    desc: (re)-build Docker image
    cmds:
      - docker-compose --build
  d:logs:
    desc: Read backend logs
    cmds:
      - docker logs backend
  d:sql:
    desc: get into sql console
    cmds:
      - docker exec -it db mysql -u $DB_USERNAME --password=$DB_PASSWORD $DB_DATABASE
  f:test:
    desc: Run unit tests in frontend
    cmds:
      - docker exec -it frontend npm run test
