name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build stack
        run: docker-compose --env-file backend/.env.example up -d
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: docker exec -it frontend npm run test
